version: '3'

services:
  # Wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
