version:                     '3'

services:

  # MySQL DB
  db:
    image:                   mysql:5.7
    restart:                 always
    environment:
      MYSQL_ROOT_PASSWORD:   password
      MYSQL_DATABASE:        wordpress
      MYSQL_USER:            wordpress
      MYSQL_PASSWORD:        wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    image:                   phpmyadmin/phpmyadmin
    restart:                 always
    environment:
      PMA_HOST:              db
      MYSQL_ROOT_PASSWORD:   password
    depends_on:
      - db
    ports:
      - '8080:80'
    networks:
      - wpsite

  # Wordpress
  wordpress:
    image:                   wordpress:latest
    restart:                 always
    volumes:                 ['./app/:/var/www/html']
    depends_on:
      - db
    ports:
      - '8000:80'
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data:
